package operation

type OperationType int

const (
	Insert OperationType = iota
	Delete
)

// write a function to transform operations

type OperationID struct {
	ClientID    string
	SequenceNum int //monotonically increasing sequence number for operations generated by the same client
}

type Operation struct {
	Type     OperationType //is operation an insertion or deletion.
	Position int           //position where operation takes place.
	Content  string        //string to be inserted for insertion; for deletion, can be empty string.
	ID       *OperationID  //unique id for operation, required for Jupiter algorithm's transformation rules.
}
